name: Publish Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          docker build -t ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:latest .
          docker tag ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:latest ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:${{ github.ref_name }}

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/yourip-app:latest
          docker push ghcr.io/${{ github.repository_owner }}/yourip-app:${{ github.ref_name }}
